### ISSUE TITLE
[document] Move Integrations to wiki?

### ISSUE THREAD

**Issue by Freed-Wu** [lambdalisue/nerdfont.vim#23]
Maybe we can move integration to <https://github.com/lambdalisue/nerdfont.vim/wiki> to allow extension developer to add their nerdfont extensions easier?

**Comment by lambdalisue** [comment]
I'm sorry but I don't get what you mean...

**Comment by Freed-Wu** [comment]
Oh, I means moving `README.md`'s integration section to wiki :smile:

**Comment by lambdalisue** [comment]
Ah, got it. Sounds good for me.
