### ISSUE TITLE
a2ac4d9 breaks existing cellwidth settings

### ISSUE THREAD

**Issue by orokasan** [lambdalisue/nerdfont.vim#27]
After a2ac4d9 , nerdfont.vim breaks cellwidth setting by `setcellwidth()` called elsewhere.
Because of  `setcellwidth()`  behavior  that overwrites existing settings.
sample script is here.

```vim
set ambiwidth=single

" ● → 0x25cf

call setcellwidths([[0x25cf, 0x25cf, 2]])

" ● is displayed double width.

call nerdfont#cellwidths#fix()

" ● is now displayed sigle width.
```

thanks.

**Comment by lambdalisue** [comment]
Probably fixed.

**Comment by orokasan** [comment]
fix confirmed. thanks!
