### ISSUE TITLE
This plugin changes the width of powerline fonts for all buffers (e.g. terminal)

### ISSUE THREAD

**Issue by Momijiichigo** [lambdalisue/nerdfont.vim#28]
With this plugin used with [fern-renderer-nerdfont.vim](https://github.com/lambdalisue/fern-renderer-nerdfont.vim), powerline fonts now take two character-spaces and it broke [terminal](https://github.com/akinsho/toggleterm.nvim) display
Before commit `213a00b1ed5ae166c12e3ba632d3108296b03667`:
![image](https://github.com/lambdalisue/nerdfont.vim/assets/46286940/927072b4-9f29-402a-8165-13d0d0475f83)
After the commit `213a00b1ed5ae166c12e3ba632d3108296b03667`:
![image](https://github.com/lambdalisue/nerdfont.vim/assets/46286940/28e86c4b-5357-4d75-b4d4-34337976ad7f)

**Comment by lambdalisue** [comment]
I see. Well, disable [autofix](https://github.com/lambdalisue/nerdfont.vim/blob/4d0ca21c69143a7d16016cbe52e342f20de5ecc0/doc/nerdfont.txt#L57-L59) by `let g:nerdfont#autofix_cellwidths = 0` for now.

**Comment by lambdalisue** [comment]
I'll remove Powerline Fonts from autofix later.

**Comment by lambdalisue** [comment]
@Momijiichigo I think the issue is solved by https://github.com/lambdalisue/nerdfont.vim/pull/29. Could you confirm and please re-open if it doesn't.

**Comment by Momijiichigo** [comment]
it's fixed! thank you!
