### ISSUE TITLE
Vue icon is broken

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/nerdfont.vim#3]
![image](https://user-images.githubusercontent.com/51912173/90006318-5741d900-dca1-11ea-8457-8351c8a5a808.png)

Hey. Vue icon is broken. However it works in airline.

vim
st-terminal
freebsd

**Comment by lambdalisue** [comment]
That one comes from https://github.com/lambdalisue/nerdfont.vim/blob/master/autoload/nerdfont/path/extension.vim#L113
so if you change it, it works.

However, current one works on my font (https://github.com/miiton/Cica) so I'd like to ask what is your font

**Comment by timsofteng** [comment]
@lambdalisue 
I'm using this font

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DejaVuSansMono

And it works in nerdtree

![image](https://user-images.githubusercontent.com/51912173/90246113-89d40900-de3c-11ea-9af6-d85d6cf352a4.png)

**Comment by lambdalisue** [comment]
It seems Cica uses a bit different glyph for Vue. Please send me a PR to replace the Vue icon to your glyph.

**Comment by lambdalisue** [comment]
It seems `fd42` is correct Vue icon in NerdFont.

![icons collection,   fonts patcher 2020-08-20 10-29-55](https://user-images.githubusercontent.com/546312/90706456-1add3100-e2d0-11ea-91e8-9a064f42872d.png)


https://www.nerdfonts.com/cheat-sheet
https://github.com/ryanoasis/vim-devicons/commit/8998fe2830c43fed9d495fb2f8917b2d3a7e4cb3
https://github.com/miiton/Cica/commit/ac115dad547963a176101b101b6ec176c238ddeb
