### ISSUE TITLE
[feature] Add gentoo

### ISSUE THREAD

**Issue by Freed-Wu** [lambdalisue/nerdfont.vim#8]
<https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L105>

**Comment by lambdalisue** [comment]
PR is welcome 👍

**Comment by Freed-Wu** [comment]
I know `expand('$OSTYPE') ==# 'linux-android'` will return truein nvim on android. I think it can be utilized to add an android icon ``. but I don't sure if it is a good idea (don't use `lsb_release`).

![image](https://user-images.githubusercontent.com/32936898/132093296-416e9f9e-e437-4ddb-b2a5-abdb4b69c669.png)

**Comment by Freed-Wu** [comment]
`$PREFIX ==# '/data/data/com.termux/files/usr'` will be better because `$OSTYPE` is an environment variable which only is know by shell and vim must use `expand` to know it.
